---
- hosts: all
  become: true
  gather_facts: yes
  vars: 
    user_name: jano2029
    group_name: devops
  vars_files: 
    - variables.yml
  tasks :
    - name: Check the time
      command : date
      when: ansible_distribution =="jano" or ansible_processor_nproc == 2

    - name : create user jano
      user: 
          name: "{{user_name}}"
          comment: jano Admin
    - name : create group
      group :
         name: "{{group_name}}"
         state: present
    - name: Install package
      package: 
        name: "{{pkg_name}}"
        state: present
